//
//  SkillTestView.swift -> SQLApp
//  Created by José Miguel Torres Chávez Nava on 20/03/26.
//

import SwiftUI

/// A showcase view demonstrating UI/UX design recommendations generated by the
/// "UI UX Pro Max" skill for an SQL learning app.
///
/// Design system applied:
/// - **Style**: Vibrant & Block-based (bold, geometric, high contrast)
/// - **Colors**: Code dark (#0F172A) + run green (#22C55E) accent
/// - **Typography mood**: Developer / technical / precise
/// - **Key effects**: Large section gaps, bold hover-like states, smooth transitions
struct SkillTestView: View {

    // MARK: - Dependencies

    /// The ViewModel for the dark-themed SQL editor, connected to user_database.sqlite.
    @Bindable var viewModel: QueryEditorViewModel

    /// Settings ViewModel providing the keyword highlight color.
    let settingsViewModel: SettingsViewModel

    // MARK: - State

    @State private var selectedStyle: DesignStyle = .vibrant
    @State private var animateHero = false
    @State private var isEditorFocused = false
    @State private var showClearButton = false

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 32) {
                    heroSection
                    stylePickerSection
                    colorPaletteSection
                    featureCardsSection
                    darkEditorSection
                    typographySection
                }
                .padding(.horizontal)
                .padding(.bottom, 40)
            }
            .background(Color(.systemGroupedBackground))
            .navigationTitle("Skill Test")
            .contentShape(Rectangle())
            .onTapGesture { dismissKeyboard() }
            .sensoryFeedback(.success, trigger: viewModel.executionStatus) { _, new in
                if case .success = new { return true }
                return false
            }
            .sensoryFeedback(.error, trigger: viewModel.executionStatus) { _, new in
                if case .error = new { return true }
                return false
            }
        }
        .onAppear {
            withAnimation(.easeOut(duration: 0.6)) {
                animateHero = true
            }
        }
    }

    // MARK: - Hero Section

    /// A bold hero banner inspired by the "Vibrant & Block-based" style,
    /// showcasing the design system's dark palette with green accents.
    private var heroSection: some View {
        VStack(spacing: 16) {
            ZStack {
                RoundedRectangle(cornerRadius: 20)
                    .fill(
                        LinearGradient(
                            colors: [
                                Color(hex: 0x0F172A),
                                Color(hex: 0x1E293B)
                            ],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )

                VStack(spacing: 12) {
                    Image(systemName: "chevron.left.forwardslash.chevron.right")
                        .font(.system(size: 44, weight: .bold))
                        .foregroundStyle(Color(hex: 0x22C55E))
                        .scaleEffect(animateHero ? 1.0 : 0.5)
                        .opacity(animateHero ? 1 : 0)

                    Text("SQLApp")
                        .font(.system(size: 28, weight: .bold, design: .monospaced))
                        .foregroundStyle(.white)

                    Text("Design System by UI UX Pro Max")
                        .font(.system(size: 13, weight: .medium, design: .rounded))
                        .foregroundStyle(Color(hex: 0x818CF8))
                }
                .padding(.vertical, 32)
            }
            .frame(height: 200)

            Text("Style: Vibrant & Block-based · Colors: Code Dark + Run Green")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }

    // MARK: - Style Picker

    /// Demonstrates how different UI styles from the skill look in practice.
    private var stylePickerSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader("Recommended Styles", icon: "paintpalette")

            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 12) {
                    ForEach(DesignStyle.allCases) { style in
                        Button {
                            withAnimation(.spring(duration: 0.3)) {
                                selectedStyle = style
                            }
                        } label: {
                            VStack(spacing: 8) {
                                Image(systemName: style.icon)
                                    .font(.title2)
                                    .frame(width: 56, height: 56)
                                    .background(
                                        selectedStyle == style
                                            ? style.accentColor.opacity(0.2)
                                            : Color(.tertiarySystemGroupedBackground)
                                    )
                                    .clipShape(RoundedRectangle(cornerRadius: 14))
                                    .overlay(
                                        RoundedRectangle(cornerRadius: 14)
                                            .stroke(
                                                selectedStyle == style
                                                    ? style.accentColor
                                                    : .clear,
                                                lineWidth: 2
                                            )
                                    )

                                Text(style.name)
                                    .font(.caption2)
                                    .fontWeight(.medium)
                            }
                            .foregroundStyle(
                                selectedStyle == style
                                    ? style.accentColor
                                    : .secondary
                            )
                        }
                        .buttonStyle(.plain)
                    }
                }
                .padding(.horizontal, 4)
            }

            // Style description card
            HStack {
                VStack(alignment: .leading, spacing: 4) {
                    Text(selectedStyle.name)
                        .font(.headline)
                    Text(selectedStyle.description)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                Spacer()
                Text(selectedStyle.bestFor)
                    .font(.caption2)
                    .padding(.horizontal, 10)
                    .padding(.vertical, 5)
                    .background(selectedStyle.accentColor.opacity(0.15))
                    .foregroundStyle(selectedStyle.accentColor)
                    .clipShape(Capsule())
            }
            .padding(14)
            .background(Color(.secondarySystemGroupedBackground))
            .clipShape(RoundedRectangle(cornerRadius: 12))
        }
    }

    // MARK: - Color Palette

    /// Shows the recommended color palette from the design system.
    private var colorPaletteSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader("Color Palette", icon: "swatchpalette")
            Text("\"Code Dark + Run Green\" — optimized for developer tools")
                .font(.caption)
                .foregroundStyle(.secondary)

            HStack(spacing: 0) {
                ForEach(paletteColors) { item in
                    VStack(spacing: 6) {
                        Rectangle()
                            .fill(item.color)
                            .frame(height: 64)

                        Text(item.label)
                            .font(.system(size: 9, weight: .medium, design: .monospaced))
                            .foregroundStyle(.secondary)

                        Text(item.hex)
                            .font(.system(size: 8, design: .monospaced))
                            .foregroundStyle(.tertiary)
                    }
                }
            }
            .clipShape(RoundedRectangle(cornerRadius: 12))
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .stroke(Color(.separator), lineWidth: 0.5)
            )
        }
    }

    // MARK: - Feature Cards (Bento-style)

    /// A Bento Grid layout demonstrating the "block-based" design approach.
    private var featureCardsSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader("Feature Showcase", icon: "square.grid.2x2")

            LazyVGrid(
                columns: [
                    GridItem(.flexible(), spacing: 12),
                    GridItem(.flexible(), spacing: 12)
                ],
                spacing: 12
            ) {
                FeatureCard(
                    icon: "terminal",
                    title: "SQL Editor",
                    subtitle: "Syntax highlighting",
                    color: Color(hex: 0x22C55E)
                )
                FeatureCard(
                    icon: "cylinder",
                    title: "Database",
                    subtitle: "Browse & inspect",
                    color: Color(hex: 0x818CF8)
                )
                FeatureCard(
                    icon: "book",
                    title: "Practice",
                    subtitle: "Guided exercises",
                    color: Color(hex: 0xF59E0B)
                )
                FeatureCard(
                    icon: "chart.bar",
                    title: "Analytics",
                    subtitle: "Track progress",
                    color: Color(hex: 0xEF4444)
                )
            }
        }
    }

    // MARK: - Dark-Themed SQL Editor

    /// A functional SQL editor styled with the "Code Preview" dark palette.
    /// Connected to user_database.sqlite for live query execution.
    private var darkEditorSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader("SQL Editor", icon: "terminal")

            VStack(spacing: 0) {
                // Terminal-style title bar
                HStack {
                    Circle().fill(.red).frame(width: 10, height: 10)
                    Circle().fill(.yellow).frame(width: 10, height: 10)
                    Circle().fill(.green).frame(width: 10, height: 10)
                    Spacer()
                    Text("QueryEditorPro.sql")
                        .font(.system(size: 11, design: .monospaced))
                        .foregroundStyle(Color(hex: 0x94A3B8))
                }
                .padding(.horizontal, 12)
                .padding(.vertical, 8)
                .background(Color(hex: 0x1E293B))

                // SQL text editor with dark background
                ZStack(alignment: .topTrailing) {
                    SQLTextEditorView(
                        text: $viewModel.sqlText,
                        isFocused: $isEditorFocused,
                        keywordColor: UIColor(Color(hex: 0x818CF8))
                    )
                    .frame(minHeight: 120, maxHeight: 180)
                    .colorScheme(.dark)

                    if showClearButton {
                        Button {
                            viewModel.sqlText = ""
                            showClearButton = false
                        } label: {
                            Text("Clear")
                                .font(.caption.bold())
                                .foregroundStyle(Color(hex: 0xF8FAFC))
                                .padding(.horizontal, 10)
                                .padding(.vertical, 5)
                                .background(Color(hex: 0x334155))
                                .clipShape(Capsule())
                        }
                        .padding(8)
                        .transition(.opacity.combined(with: .scale(scale: 0.8)))
                    }
                }
                .background(Color(hex: 0x0F172A))
                .animation(.easeInOut(duration: 0.2), value: showClearButton)
                .onChange(of: isEditorFocused) { _, focused in
                    if focused && !viewModel.sqlText.isEmpty {
                        showClearButton = true
                    } else {
                        showClearButton = false
                    }
                }
                .onChange(of: viewModel.sqlText) {
                    if showClearButton { showClearButton = false }
                }

                // Control bar
                HStack(spacing: 12) {
                    Button {
                        dismissKeyboard()
                        Task { await viewModel.executeSQL() }
                    } label: {
                        HStack(spacing: 6) {
                            if viewModel.isExecuting {
                                ProgressView()
                                    .tint(Color(hex: 0x0F172A))
                                    .controlSize(.small)
                            } else {
                                Image(systemName: "play.fill")
                                    .font(.system(size: 12))
                            }
                            Text("Run")
                                .font(.system(size: 13, weight: .semibold, design: .monospaced))
                        }
                        .foregroundStyle(Color(hex: 0x0F172A))
                        .padding(.horizontal, 16)
                        .padding(.vertical, 8)
                        .background(Color(hex: 0x22C55E))
                        .clipShape(RoundedRectangle(cornerRadius: 8))
                    }
                    .disabled(
                        viewModel.sqlText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                        || viewModel.isExecuting
                    )
                    .opacity(
                        viewModel.sqlText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                        ? 0.5 : 1.0
                    )

                    if let message = viewModel.executionMessage {
                        Text(message)
                            .font(.system(size: 11, design: .monospaced))
                            .foregroundStyle(darkEditorMessageColor)
                    }

                    Spacer()

                    if darkEditorHasResults {
                        Button {
                            viewModel.clearResults()
                        } label: {
                            Image(systemName: "xmark.circle.fill")
                                .font(.system(size: 14))
                                .foregroundStyle(Color(hex: 0x94A3B8))
                        }
                    }
                }
                .padding(.horizontal, 12)
                .padding(.vertical, 8)
                .background(Color(hex: 0x1E293B))
            }
            .clipShape(RoundedRectangle(cornerRadius: 12))

            // Results area
            if let error = viewModel.errorMessage {
                ScrollView {
                    HStack(alignment: .top, spacing: 8) {
                        Image(systemName: "xmark.circle.fill")
                            .foregroundStyle(Color(hex: 0xEF4444))
                        Text(error)
                            .font(.system(size: 12, design: .monospaced))
                            .foregroundStyle(Color(hex: 0xF8FAFC))
                    }
                    .padding(12)
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
                .frame(maxHeight: 100)
                .background(Color(hex: 0x0F172A))
                .clipShape(RoundedRectangle(cornerRadius: 10))
            } else if let result = viewModel.queryResult {
                StyledResultsTableView(result: result, style: settingsViewModel.selectedStyle)
                    .frame(minHeight: 120, maxHeight: 250)
                    .clipShape(RoundedRectangle(cornerRadius: 10))
            }
        }
    }

    /// Color for the execution message in the dark editor.
    private var darkEditorMessageColor: Color {
        switch viewModel.executionStatus {
        case .error: Color(hex: 0xEF4444)
        case .success: Color(hex: 0x22C55E)
        case .idle: Color(hex: 0x94A3B8)
        }
    }

    /// Whether the dark editor has any results to show.
    private var darkEditorHasResults: Bool {
        viewModel.queryResult != nil || viewModel.errorMessage != nil || viewModel.executionMessage != nil
    }

    // MARK: - Typography

    /// Demonstrates the recommended font pairing from the design system.
    private var typographySection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader("Typography", icon: "textformat")
            Text("Recommended: Monospaced (code) + Rounded (UI)")
                .font(.caption)
                .foregroundStyle(.secondary)

            VStack(alignment: .leading, spacing: 16) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Monospaced — Code & Data")
                        .font(.system(size: 11, weight: .medium))
                        .foregroundStyle(.secondary)
                    Text("SELECT * FROM tables;")
                        .font(.system(size: 18, weight: .semibold, design: .monospaced))
                }

                Divider()

                VStack(alignment: .leading, spacing: 4) {
                    Text("Rounded — UI Elements")
                        .font(.system(size: 11, weight: .medium))
                        .foregroundStyle(.secondary)
                    Text("Learn SQL Interactively")
                        .font(.system(size: 18, weight: .semibold, design: .rounded))
                }

                Divider()

                VStack(alignment: .leading, spacing: 4) {
                    Text("Default — Body Text")
                        .font(.system(size: 11, weight: .medium))
                        .foregroundStyle(.secondary)
                    Text("Practice real queries on real databases with instant feedback and guided exercises.")
                        .font(.system(size: 15))
                        .foregroundStyle(.secondary)
                }
            }
            .padding(16)
            .background(Color(.secondarySystemGroupedBackground))
            .clipShape(RoundedRectangle(cornerRadius: 12))
        }
    }

    // MARK: - Helpers

    private func sectionHeader(_ title: String, icon: String) -> some View {
        Label(title, systemImage: icon)
            .font(.title3)
            .fontWeight(.bold)
    }

    /// Dismisses the keyboard by resigning the current first responder.
    private func dismissKeyboard() {
        UIApplication.shared.sendAction(
            #selector(UIResponder.resignFirstResponder),
            to: nil, from: nil, for: nil
        )
    }
}

// MARK: - Feature Card Component

/// A single feature card for the Bento Grid section.
private struct FeatureCard: View {
    let icon: String
    let title: String
    let subtitle: String
    let color: Color

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            Image(systemName: icon)
                .font(.title2)
                .foregroundStyle(color)
                .frame(width: 40, height: 40)
                .background(color.opacity(0.15))
                .clipShape(RoundedRectangle(cornerRadius: 10))

            Text(title)
                .font(.subheadline)
                .fontWeight(.semibold)

            Text(subtitle)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(16)
        .background(Color(.secondarySystemGroupedBackground))
        .clipShape(RoundedRectangle(cornerRadius: 14))
    }
}

// MARK: - Design Style Enum

/// The styles recommended by the UI UX Pro Max skill for an SQL learning app.
enum DesignStyle: String, CaseIterable, Identifiable {
    case vibrant = "vibrant"
    case glassmorphism = "glassmorphism"
    case minimalism = "minimalism"
    case darkMode = "darkMode"
    case bentoGrid = "bentoGrid"

    var id: String { rawValue }

    var name: String {
        switch self {
        case .vibrant: "Vibrant & Block"
        case .glassmorphism: "Glassmorphism"
        case .minimalism: "Minimalism"
        case .darkMode: "Dark Mode"
        case .bentoGrid: "Bento Grid"
        }
    }

    var icon: String {
        switch self {
        case .vibrant: "square.grid.3x3.fill"
        case .glassmorphism: "rectangle.on.rectangle"
        case .minimalism: "minus.circle"
        case .darkMode: "moon.fill"
        case .bentoGrid: "square.grid.2x2"
        }
    }

    var description: String {
        switch self {
        case .vibrant: "Bold, energetic, block layout with geometric shapes and high color contrast."
        case .glassmorphism: "Frosted glass effects with transparency, blur backgrounds, and subtle borders."
        case .minimalism: "Clean, focused, generous whitespace. Content takes center stage."
        case .darkMode: "OLED-optimized dark surfaces with vibrant accent colors for dev tools."
        case .bentoGrid: "Modular grid layout inspired by Japanese bento boxes for feature showcases."
        }
    }

    var bestFor: String {
        switch self {
        case .vibrant: "Startups"
        case .glassmorphism: "SaaS"
        case .minimalism: "Enterprise"
        case .darkMode: "Dev Tools"
        case .bentoGrid: "Dashboards"
        }
    }

    var accentColor: Color {
        switch self {
        case .vibrant: Color(hex: 0x22C55E)
        case .glassmorphism: Color(hex: 0x818CF8)
        case .minimalism: Color(hex: 0x64748B)
        case .darkMode: Color(hex: 0xF59E0B)
        case .bentoGrid: Color(hex: 0xEF4444)
        }
    }
}

// MARK: - Palette Color Data

/// A single entry in the color palette display.
private struct PaletteColor: Identifiable {
    let id = UUID()
    let label: String
    let hex: String
    let color: Color
}

/// The recommended palette from the "Code Dark + Run Green" design system.
private let paletteColors: [PaletteColor] = [
    PaletteColor(label: "Primary", hex: "#1E293B", color: Color(hex: 0x1E293B)),
    PaletteColor(label: "Secondary", hex: "#334155", color: Color(hex: 0x334155)),
    PaletteColor(label: "CTA", hex: "#22C55E", color: Color(hex: 0x22C55E)),
    PaletteColor(label: "Background", hex: "#0F172A", color: Color(hex: 0x0F172A)),
    PaletteColor(label: "Text", hex: "#F8FAFC", color: Color(hex: 0xF8FAFC)),
    PaletteColor(label: "Accent", hex: "#818CF8", color: Color(hex: 0x818CF8)),
]

// MARK: - Preview

#Preview {
    SkillTestView(
        viewModel: QueryEditorViewModel(
            databaseService: SQLiteDatabaseService(databaseName: "Preview.sqlite")
        ),
        settingsViewModel: SettingsViewModel()
    )
}
